#!/usr/bin/env sh

ZK_PATH="${HOME}/Documents/obsidian/Knowledge"

cd "$ZK_PATH"

GIT_BRANCH='main'
CURRENT_DATE=$(date +"%F %H:%M:%S")
CHANGES_EXIST=$(git status --porcelain | wc -l)

if [ $CHANGES_EXIST -eq 0 ]; then
	exit 0
fi

git add -A
git commit -qm "Last Sync: ${CURRENT_DATE}"
git push -qu origin $GIT_BRANCH
